baseurl: "/"
languageCode: "en-us"
title: "ERD's website"
theme: "hugo-xmin"
googleAnalytics: "UA-131380665-2"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
preserveTaxonomyNames: true
enableEmoji: true

permalinks:
    post: "/post/:year/:month/:day/:slug/"
    note: "/note/:year/:month/:day/:slug/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Credits
      url: /credits/
      weight: 5

params:
    description: "A website built through Hugo and blogdown."
    footer: "&copy; [Edgardo Rivera-Delgado](https://riveradelgado.com) 2019 |  [LinkedIn](https://www.linkedin.com/in/riveradelgado/) | [Github](https://github.com/eriveradelgado) | [Twitter](https://twitter.com/eriveradelgado)"
    highlightjsVersion: "11.0.1"
    highlightjsCDN: "//cdn.bootcss.com"
    highlightjsLang: ["r", "yaml"]
    highlightjsTheme: "papercolor-light"
    MathJaxCDN: "//cdn.bootcss.com"
    MathJaxVersion: "2.7.1"

markup:
  goldmark:
    renderer:
      unsafe: true
