baseurl = "/"
languageCode = "en-us"
title = "ERD's website"
theme = "hugo-xmin"
googleAnalytics = "UA-131380665-2"
disqusShortname = "riveradelgado-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Edgardo Rivera-Delgado](https://riveradelgado.com) 2019 | [LinkedIn](https://www.linkedin.com/in/riveradelgado/) | [Github](https://github.com/eriveradelgado) | [Twitter](https://twitter.com/eriveradelgado)"
